### ISSUE TITLE
Error running on local setup: No subject set in vapidDetails.subject

### ISSUE THREAD

**Issue by sibongumusa14** [muzam1l/tclone-api#11]
evert time i start the api this error shows up, then causing it to crash, i think it is a problem with web-push

**Comment by muzam1l** [comment]
For running this on local you need to set these environmental variables, which you can have in your `.env` file in root of your project
```
# Push notifications keys. You can generate them with command "./node_modules/.bin/web-push generate-vapid-keys"
PUBLIC_VAPID_KEY=<public vapid key, which goes into your front-end too>
PRIVATE_VAPID_KEY=<corresponding private key>
# This must be either a URL or a 'mailto:' address.
# For example: 'https://my-site.com/contact' or 'mailto: contact@my-site.com'
WEB_PUSH_CONTACT="mailto: mail@somewhere.com"
```

Are you setting those, let me know

**Comment by sibongumusa14** [comment]
> For running this on local you need to set these environmental variables, which you can have in your `.env` file in root of your project
> 
> ```
> # Push notifications keys. You can generate them with command "./node_modules/.bin/web-push generate-vapid-keys"
> PUBLIC_VAPID_KEY=<public vapid key, which goes into your front-end too>
> PRIVATE_VAPID_KEY=<corresponding private key>
> # This must be either a URL or a 'mailto:' address.
> # For example: 'https://my-site.com/contact' or 'mailto: contact@my-site.com'
> WEB_PUSH_CONTACT="mailto: mail@somewhere.com"
> ```
> 
> Are you setting those, let me know

Thanks first time using webpush, you did a great job on the tclone

**Comment by muzam1l** [comment]
Vl keep this issue open for now until I write build section in Readme.

**Comment by muzam1l** [comment]
Added Deploy section now.
